logging:
  level:
    root: info
spring:
  application:
    name: test
# Redis数据库索引（默认为0）
  redis:
    database: 0
  # Redis服务器地址
    host: 106.13.71.149
  # Redis服务器连接端口
    port: 6789
  # Redis服务器连接密码（默认为空）
    #password: "@lijunyoucan541288..|"
    password: "@lijunyoucan54188..|"
  # 连接超时时间（毫秒）
    timeout: 300
  thymeleaf:
    # 默认路径
    prefix: classpath:/templates/
    # 后缀
    suffix: .html
    # 模板格式
    mode: HTML5
    encoding: utf-8
    cache: false
server:
  port: 8082
