logging:
  level:
    root: info
server:
  port: 8083
spring:
  thymeleaf:
    # 默认路径
    prefix: classpath:/templates/
    # 后缀
    suffix: .html
    # 模板格式
    mode: HTML5
    encoding: utf-8
    cache: false